xen-troops/meta-xt-prod-cockpit-rcar

meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper-toolchain-native.bb, meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper_git.bb
The toolchain from meta-arm produces the binary file
that does not work. The version  10-2020-q4-major of arm-none-eabi
produces good binary file.
Signed-off-by: Ihor Usyk <ihor.usyk@gmail.com>
=> cluster_wrapper: add toolchain to build cluster.

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/doma.bbappend, meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-set-root.conf
There are no dependencies on sndbe and displbe inside doma.service,
so no need for modifications in our append.
Also, call of doma-set-root is remade as systemd drop-in file.
-----
NOTE: must be merged after https://github.com/xen-troops/meta-xt-common/pull/20
=> dom0: Remove modifications of doma.service file

meta-xt-prod-cockpit-rcar-driver-domain/recipes-core/images/core-image-minimal.bbappend
Add iotop and fio to be able to measure IO.
=> domd: add IO performance utilities to the resulting image

meta-xt-prod-cockpit-rcar-control/recipes-core/images/core-image-thin-initramfs.bbappend
Add xen-tools-xenstat, which provides xentop
to the resulting dom0 image.
=> dom0: add xentop to the resulting image

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/xen/files/0001-xen-HACK-disable-warning-delay.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/xen/xen_git.bbappend
Disable warning delay to speed up start by 3 sec.
=> xen: HACK: disable warning delay

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-h3ulcb-4x2g-kf.cfg
There is no need to request DHCP for Linux
kernel, since all configurations should be static, or
applied on the later boot stages.
=> doma: do not force DHCP for linux kernel

prod-cockpit-rcar.yaml
- Add missed layer 
- Remove PREFFERED version and providers for GLES
This PR solves the build issue:
```
ERROR: gles-user-module-1.0-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'file://r8a77951_linux_gsx_binaries_gles.tar.bz2')
```
=> yaml: Fix GLES related part

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.cpp, meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.h
The type of method in declaration and type in implementation were different. What was the reason of build error.
Fixed.
=> vis-service: fix build error of VisClient::getGearSelection

meta-xt-prod-cockpit-rcar-driver-domain/recipes-core/images/core-image-minimal.bbappend
The service dual-render-3d-part is not used anymore.
=> domd: remove dual-render-3d-part from build

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/cluster-view/cluster-view_git.bb
Some files were not in the list of SRC_URI.
There are
images/SPORT_on.png
images/SPORT_off.png
images/Auto_Lighting_on.png
images/Turn_right_off.png
images/Auto_Lighting_off.png
images/Turn_left_off.png
images/Cruise_control_on.png
commandline.cpp
commandline.h
qml/Footer.qml \
qml/Footer.qml \
qml/OdoInfo.qml \
qml/SpeedLimitInfo.qml \
qml/TimeInfo.qml \
qml/TripInfo.qml \
qml/WeatherInfo.qml
=> cluster-view: fix build error

meta-xt-prod-cockpit-rcar-driver-domain/recipes-core/base-files/base-files_%.bbappend
We see that execution of 'resize' affects some applications during SSH connection. Also this command used only for interactive console.
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
=> Avoid resizing of console for SSH connections

meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper_git.bb
The branch has been renamed according to the business goal.
=> cluster wrapper: set the source of branch CES-2023

doc/Dockerfile
pygit2 has been updated in pip repos and now requires the version of libgit that is not present in Ubuntu repos. To fix this, install prebuilt pygit2 directly from the Ubuntu repos.
=> docker: Fix pygit2 installation

prod-cockpit-rcar.yaml
This is needed to make the build more reliable.
=> prod-cockpit-rcar.yaml Fix version for xt repos

meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/defconfig
Enable the PV camera frontend for shared video use-case. The idea is to share the stream from the same hardware device between two domains (DomD and DomA). In order to run the frontend in DomD we will need the hotplug support for PV camera since the backend is also in DomD.
=> domd/kernel: Enable CONFIG_MEDIA_XEN_FRONTEND

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-pvcamera.cfg
In order to use all of them in the guest.
Please note, the format "BA24" suits us better than "YUYV". DomD's counterpart should use the same format for the video sharing to work.
=> doma-pvcamera.cfg: Assign all LVDS cameras

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-h3ulcb-4x2g-kf.cfg, meta-xt-prod-cockpit-rcar-control/recipes-guests/domd/files/domd-h3ulcb-4x2g-kf.cfg
The upcoming camera use-cases (with up to 4 cameras per each guest and up to 4 buffers with resolution 1280x1080 per each camera being involved) will require some additional memory in DomD to allocate buffers for streaming as well as buffers for mapping guest pages into.
While increasing the whole Dom's memory (1536MB), increase also xt_page_pool (192MB) and cma (256MB) pools. Of course, in order to achieve that we have to borrow some memory from DomA.
=> domd.cfg/doma.cfg: Rearrange RAM assigned to the guests

meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/capture/capture_1.0.bbappend, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/capture/files/0001-Change-default-camera-list.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/capture/files/0001-Proccess-an-image-in-case-of-DRM-as-well-out_fb-is-n.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/capture/files/0002-Add-support-for-LVDS-cameras.patch
Override the capture sources with newer one from Renesas. Add patches for DRM mode and virtual cameras support.
This tools is needed to show camera streams on a system without proper graphics environment.
Example launch command:
capture -d /dev/video6 -W 1280 -H 1080 -f rgb32i  -z -c 10000 -L 0 -T 0 -D 4
=> domd/camera: Integrate capture tool

meta-xt-prod-cockpit-rcar-control/recipes-core/images/core-image-thin-initramfs.bbappend
Camera hotplug makes no sense without pvcamera support, so make it dependent on the pvcamera feature.
=> dom0: Move camera-hotplug under pvcamera distro feature

meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_git.bbappend, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0001-pfc-h3-Configure-DU_DISP-pin.patch
All details are inside supplied patch.
=> bl2: Properly configure DU_DISP pin for VGA->HMDI use case in CR7

README.md, prod-cockpit-rcar.yaml
The meta-aos had the reference at the branch 'main', what is not good for the fixed release.
Besides, the override for the ENABLE_AOS has been removed as unnecessary.
=> prod-cockpit0rcar.yaml: fix revision of meta-aos

prod-cockpit-rcar.yaml
Change manifest repository to github based, in terms of moving open projects to github.
=> doma: change manifest repository to github based

prod-cockpit-rcar.yaml
Additional patch "libxl/arm: provide guests with random seed" added on top of Xen tree, so updating revision.
=> yaml: update revision of the XT_XEN_REVISION

prod-cockpit-rcar.yaml
Now, all required packages are placed under 'default' packages. The notdefault is not necessary
=> prod-cockpit-rcar.yaml, doma: remove notdefault group

prod-cockpit-rcar.yaml
Introduce the XT_DOMA_KERNEL_BUILD_CONFIG variable, which allows for the selection of different kernel configurations based on specific use cases. This variable provides the flexibility to choose the appropriate kernel configuration depending on the requirements of each use case.
For instance, when opting for prebuilts, the kernel configuration can be adjusted to include fewer modules.
=> yaml: introduce XT_DOMA_KERNEL_BUILD_CONFIG variable

prod-cockpit-rcar.yaml
It allows using the same configuration groups to reduce the number of errors.
=> prod-cockpit-rcar, doma_kernel: usage doma groups.

meta-xt-prod-cockpit-rcar-driver-domain/recipes-support/bmap-tools/bmap-tools_3.5.bbappend
Intel renamed 'master' branch to 'main' so we
have to overwrite SRC_URI accordingly.
=> domd: update branch for bmap-tools

scripts/ic-update/metadata.json
The component name has been changed according to the name of the component at aosadge.(see https://oem.aoscloud.io/oem/systems, name 'rcar-multinode-zephyr')
=> metadata.json: change the name of the component

meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_git.bbappend, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0001-plat-renesas-rcar-bl31-Enable-RPC-access-if-necessar.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0001-rcar_scmi_clocks.c-fix-build-error-no-returned-value.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0001-scmi-i2c-add-scmi-clock-to-i2c2.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0002-tools-Produce-two-cert_header_sa6-images.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0003-Add-bldcmd.sh.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0005-rcar-Add-DRAM2_NS_SCMI-memory-region-to-BL31-mapping.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0006-rcar-add-SCMI-reset-protocol-implementation.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0007-rcar-add-SCMI-clock-protocol-implementation.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0008-rcar-add-SCMI-stub-power-protocol-implementation.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0008-sip_sv-rollback-the-service-to-support-scmi.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0009-rcar-SCMI-base-protocol-implementation-and-handling.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0010-rcar-scmi-add-physical-resources-to-SCMI-devices.patch, meta-xt-prod-cockpit-rcar-driver-domain/recipes-bsp/arm-trusted-firmware/files/0011-bldcmd.sh-build-scmi-platform-by-default.patch
Add support of the scmi clocks to ATF.
The reason, why the scmi has been introduced is to provide the restart of the DomA domain. Without scmi protocol, the USB is not restarted what does not allow to run android GUI properly, because it requires the input device.
=> atf, i2c: add scmi-clock.

meta-xt-prod-cockpit-rcar-control/recipes-core/images/core-image-thin-initramfs.bbappend, prod-cockpit-rcar.yaml
The recipe has just a declaration
IMAGE_INSTALL_append = " xen-tools-xenstat"
It is reasonable to move it into the prod-cockpit-rcar.yaml, this is the step to reduce the number of the recipes with variables declarations and without any business functionality.
=> dom0: remove core-image-thin-initramfs.bbappend

meta-xt-prod-cockpit-rcar-driver-domain/recipes-support/bmap-tools/bmap-tools_3.5.bbappend, prod-cockpit-rcar.yaml
The reason of the change is to remove the recipes where just a global variables are changed. It is reasonable to declare the variables in the corresponded section of the yaml file.
=> domd, bmap-tools: remove recipe and declare SRC_URI in yaml file

prod-cockpit-rcar.yaml
Reason: branch master does not exist anymore
=> bmap-tools-native: add SRC_URI to prod-cockpit-rcar.yaml

doc/Dockerfile
Do not use ~ in the PATH environment variable, since Docker will insert it without expansion, and
originally ~ is a bash function for
tilde expansion. Therefore, non-bash applications will not recognize that part of the PATH.
This patch also switches ENV to the original syntax.
=> docker: fix PATH variable
