xen-troops/meta-xt-prod-cockpit-rcar

README.md
meta-xt-prod-cockpit-rcar-cluster/conf/layer.conf
meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper_git.bb
prod-cockpit-rcar.yaml

Use ENABLE_CLUSTER yes to compile the Instrument Cluster application.

cluster_wrapper: introduce the build of cluster_wrapper.bin

---

doc/u-boot-env.txt

u-boot-env: add file with the description of flashing.

---

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/u-boot-android.bbappend

Cockpit demo will have specific pathces on u-boot.

doma: override doma u-boot branch from common project

---

prod-cockpit-rcar.yaml

prod-cockpit-rcar.yaml: add mossed layers to 'domd'

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.cpp
meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.h

Fix build error in VisClient.cpp

Gearposition build error

---

meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper_git.bb

cluster_wrapper: fix revision of sport-mode

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/cluster-view/cluster-view_git.bb

cluster-view: service is 'auto-starting'

---

doc/Docker.md
doc/Dockerfile
doc/run_docker.sh
prod-cockpit-rcar.yaml

- add Docker
- minor fix for image creation

 Misc updates for cockpit demo

---

doc/Android.md

doc: add documentation for manual Android build

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.cpp
meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.h

The driver has been changed at misc one.

vis-service: change the taurus driver

---

prod-cockpit-rcar.yaml

prod-cockpit-rcar.yaml: change linux SRC_URI at github.com:xen-troops

---

meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/doma.bbappend
meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-pvcamera.cfg
meta-xt-prod-cockpit-rcar-control/recipes-guests/doma/files/doma-pvcamera.conf
meta-xt-prod-cockpit-rcar-driver-domain/recipes-core/images/core-image-minimal.bbappend

Add support for camerabe build for DomD. Add configs for systemd and DomA to support pvcamera.

pvcamera: Introduce pvcamera

---

prod-cockpit-rcar.yaml

The revisions of the meta layers are fixed.

prod-cockpit-rcar.yaml: fix Release REL-1.0

---

meta-xt-prod-cockpit-rcar-control/recipes-extended/xen/files/0001-WIP-toolstack-Hotplug-support-for-vcamera.patch
meta-xt-prod-cockpit-rcar-control/recipes-extended/xen/xen-tools_git.bbappend

The example of the hotplug command is:
xl vcamera-attach DomD backend=DomD be-alloc=0 unique-id=video0:media0
max-buffers=4 format=AR12,resolution=1280x1080

[WIP] toolstack: Hotplug support for vcamera

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/0001-HACK-media-xen-front-Guess-the-size-of-camera-buffer.patch
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/linux-renesas_%.bbappend

All details regarding an issue and proposed temporary solution you can find in attached patch.

domd/kernel: Workaround for PV camera to get second frontend functional

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/camerabe/files/camera_be.cfg

As we are going to use all cameras simultaneously in DomD/DomA.

camera_be.cfg: Configure media pipeline for all LVDS cameras

---

meta-xt-prod-cockpit-rcar-control/recipes-core/images/core-image-thin-initramfs.bbappend
meta-xt-prod-cockpit-rcar-control/recipes-extended/camera-hotplug/camera-hotplug.bb
meta-xt-prod-cockpit-rcar-control/recipes-extended/camera-hotplug/files/camera-hotplug.service

Add systemd service that will autohotplug cameras for DomD after the camerabe is ready.

dom0: Implement automatic pvcamera hotplug for DomD

---

prod-cockpit-rcar.yaml

To be able to pull all changes located in that branch.

prod-cockpit-rcar.yaml: Switch to camera-sharing-main branch

---

README.md
meta-xt-native-tools/recipes-fsdata/fsdata/files/main.cpp
meta-xt-native-tools/recipes-fsdata/fsdata/fsdata-native.bb
prod-cockpit-rcar.yaml

1. Replace C-style at C++ one.
2. Now there are 2 input parameters
- input directory
- output directory
3. simplify the configuration in .yml file
4. deploy the output file in 'deploy' directory

fsdata: improve the source code

---

meta-xt-prod-cockpit-rcar-cluster/recipes-cluster/cluster-bin/cluster-wrapper_git.bb
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a7795-h3ulcb-4x2g-kf-doma.dtsi
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a7795-h3ulcb-4x2g-kf-hdmi-doma.dts
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a7795-h3ulcb-4x2g-kf-lvds-doma.dts
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-4x2g-kf-domd.dtsi
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-4x2g-kf-hdmi-domd.dts
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/files/r8a77951-h3ulcb-4x2g-kf-lvds-domd.dts
meta-xt-prod-cockpit-rcar-driver-domain/recipes-kernel/linux/linux-renesas_%.bbappend
prod-cockpit-rcar.yaml

1. support hdmi display](cluster-wrapper: Introduce the BRANCH for hmdi and lvds displays)
2. doma, domd: decompose the device tree to support second hdmi

Support HDMI display

---

prod-cockpit-rcar.yaml

The commit is required to freeze REL-v2.0 branch.
Signed-off-by: Dmytro Klimenko <dmytro_klimenko@epam.com>
Acked-by: Ihor Usyk <ihor_usyk@epam.com>

prod-cockpit-rcar.yaml: Freeze release

---

prod-cockpit-rcar.yaml

Carla simulation camera streaming support was added to EVS Hardware stack.

EVS Carla streaming camera integration.

---

meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/cluster-view/files/main.qml
meta-xt-prod-cockpit-rcar-driver-domain/recipes-extended/vis-service/files/VisClient.cpp

Modify VisClient to use ioctl instead of write to update cluster values. 
Remove speed limit info.
Signed-off-by: Dmytro Klimenko dmytro_klimenko@epam.com

Demo CES2024 updates integration.
